Use `.xcode-version` to track Xcode version

diff --git a/.buildkite/shared-pipeline-vars b/.buildkite/shared-pipeline-vars
--- a/.buildkite/shared-pipeline-vars
+++ b/.buildkite/shared-pipeline-vars
@@ -5,4 +5,15 @@
 
 CI_TOOLKIT_PLUGIN_VERSION="6.0.1"
 
+SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
+
+XCODE_VERSION_FILE="$SCRIPT_DIR/../.xcode-version"
+if [[ ! -s "$XCODE_VERSION_FILE" ]]; then
+    echo "Error: '$XCODE_VERSION_FILE' not found or empty." >&2
+    exit 1
+fi
+# The ~> modifier is not currently used, but we strip it just in case
+XCODE_VERSION=$(sed -E 's/^~> ?//' "$XCODE_VERSION_FILE")
+
+export IMAGE_ID="xcode-$XCODE_VERSION"
 export CI_TOOLKIT_PLUGIN="automattic/a8c-ci-toolkit#$CI_TOOLKIT_PLUGIN_VERSION"
